### PR TITLE
Update major version to 974

### PR DESCRIPTION
**Pull request by krumware**
This branch updates the major version of IB Gateway to 974 from the QuantConnect builds.
Also included:
 - Logs folder added to .gitignore
 - Default Logs folder added to Dockerfile and mkdir
 - Dos2Unix added as helper for windows system usage
 - IBController.ini and jts.ini copied to image in Dockerfile to allow for volume-less running
 - Default user updated to `fdemo` (previously `edemo`)
 - jts.ini updated with new settings (apologies for the formatting update, this was done to fix line endings)

### CODE REVIEW

**Comment by krumware** [comment]
@mvberg, I don't think this closes #4, but I included a change to the username here.  I still want to see if we come across info about the default users.
 -- edit: I missed your commit 3 hours ago which accomplishes the same --

Also, I'm on the fence about the need for the dos2unix additions. Despite my usage of `git config --global core.autocrlf true`, sometimes other windows users still have trouble with building and line-endings (one of those cases here for me)

**Comment by krumware** [comment]
There is also more room for Dockerfile optimization, but that is outside of this PRs responsibility.

**Comment by mvberg** [comment]
LGTM. Thanks @krumware!

> Also, I'm on the fence about the need for the dos2unix additions.

i don't think it hurts

**Comment by krumware** [comment]
Thanks for the merge! Side note, do you want to tag this and the old version as releases/tags? In case others prefer the previous image

**Comment by mvberg** [comment]
> Side note, do you want to tag this and the old version as releases/tags?

yes, seems it is time to do proper "versioning" and also maybe set up CI to publish to a registry ... 

added you a collab - any experience with [Cirrus CI](https://cirrus-ci.org/)? haven't been in the OSS world in some time :)

**Comment by krumware** [comment]
Thanks for the invite! I don't with Cirrus in particular. But I think in this case it is probably simple enough to sign up free account or org on Docker Cloud and manually add the tags to the automatic build configurations with a regex for the tags.

**Pull request merged**
